---
title: "Untitled"
output: 
  html_document:
      toc: true
      toc_float:
          collapsed: true
        toc_depth: 2
date: `r sys.Date()`
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE,message = FALSE)
library(tidyverse)
library(easystats)
library(plotly)
library(janitor)
library(kableExtra)
library(patchwork)

getwd()

?read.csv2

df <- read.csv2("../Data/mee312226-sup-0003-datas1.csv", sep = ";") %>% 
  clean_names()

df <- read.csv("../Data/mee312226-sup-0003-datas1.csv") %>% 
  clean_names()

class(df)

df %>% clean_names()


df %>% 
  kable() %>% 
  kable_classic(lightable_options = 'hover') %>% 
  scroll_box(height=4)



```

This data set is of humerus, femur, and tibia measurements in birds. Our goal is to see if we can build a model that uses these measures to predict body mass.



### cleaning

We have to do a few tidying tasks first

```{r}

df %>% 
  mutate(femoral_pneumaticity = case_when(
    femoral_pneumaticity == "yes" ~TRUE,
    femoral_pneumaticity == "no" ~FALSE) %>% 
      as.logical(),
    body_mass_log10=log10(body_mass_g)




df[which(df$species %>%  duplicated()),]

mod



#(does summary but puts it into a data frame for you)


```

A couple of species are present more than once in this data set with different measurements:

```{r}

df %>% 
  filter(species %in% df[which(df$species %>% duplicated()),]species)



```
### visualizing
```{r}
femur <- df %>% 
  pivot_longer(starts_with("femur_"),
               names_to = "measurement", 
               names_prefix = "femur_",
               values_to="mm")
  ggplot(aes(x=mm,
             y=body_mass_g))+
    geom_point() +
    geom_smooth()+
    facet_wrap(~measurement, scales='free')+
    labs(y="Body mass (g)", x="Length (mm)", title="Femur measurements")
  
humerus

femur <- df %>% 
  pivot_longer(starts_with("humerus_"),
               names_to = "measurement", 
               names_prefix = "humerus_",
               values_to="mm")
  ggplot(aes(x=mm,
             y=body_mass_g))+
    geom_point() +
    geom_smooth()+
    facet_wrap(~measurement, scales='free')+
    labs(y="Body mass (g)", x="Length (mm)", title="humerus measurements")
  
tibia <- df %>% 
  pivot_longer(starts_with("tibia_"),
               names_to = "measurement", 
               names_prefix = "tibia_",
               values_to="mm")
  ggplot(aes(x=mm,
             y=body_mass_g))+
    geom_point() +
    geom_smooth()+
    facet_wrap(~measurement, scales='free')+
    labs(y="Body mass (g)", x="Length (mm)", title="Tibia measurements")

femur / humerus / tibia
```

### modeling

```{r}
mod1 <- glm(data=df,
          formula=body_mass_log10~(humerus_length + 
            humerus_circumference +
            femur_length+
            femur_circumference +
            tibia_length + 
            tibia_circumference)*femoral_pneumaticity)


mod <- glm(data=df,
           formula-body_mass_log10 ~ humerus_length)

step <- MASS::stepAIC(mod1,direction = 'backward')


mod1 %>% 
  broom::tidy() %>% 
  dplyr::filter(p.value<=0.05) %>% 
  kable() %>% 
  kable_classic(lightable_options='hover')


```

how well does our model predict body mass?
```{r, fig.height=3,fig.width=3,fig.align='center'}
modelr::add_predictions(df,mod1) %>% 
  mutate(pred_g=pred^10,
         residuals=abs(body_mass_g - pred_g)) %>% 
  ggplot(aes(x=pred_g,y=body_mass_g))+
  geom_point()+
  geom_smooth(linetype=2,color='red')



```

